baseurl         = "/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = "codeesthete"
paginate        = 6

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Code Esthete"
subtitle    = "I help professional developers to feel beauty of the code."
author = "Yurii Pitomets"
authorAvatar = "upload/img/standart/avatar.jpg"
authorLocation = "Houston, TX, USA"
authorWebsite = "https://yuppi.com.ua"
authorDescription = "Software developer, Founder of startup"
ageNotFoundTitle = "404 - Page not found"
description = "I help professional developers to feel beauty of the code."
metaDescription = "I help professional developers to feel beauty of the code."
pageTitle = "Page"
pageOf = "of"

[languages.ru]
languageName = "Russian"
weight = 2
title = "Code Esthete"
subtitle    = "Я помогаю профессиональным разработчикам чувствовать красоту кода."
author = "Юрий Питомец"
authorAvatar = "upload/img/standart/avatar.jpg"
authorLocation = "Хьюстон, Техас, США"
authorWebsite = "https://yuppi.com.ua"
authorDescription = "Разрабочик программного обеспечения, Основатель стартапа"
pageNotFoundTitle = "404 - Страница не найдена"
description = "Я помогаю профессиональным разработчикам чувствовать красоту кода."
metaDescription = "Я помогаю профессиональным разработчикам чувствовать красоту кода."
pageTitle = "Страница"
pageOf = "из"

[[languages.en.menu.main]]
url = "/en"
name = "Home"
weight = 200

[[languages.en.menu.main]]
url = "/en/about"
name = "About me"
weight = 190

[[languages.en.menu.main]]
url = "/en/contact"
name = "Contact me"
weight = 180

[[languages.ru.menu.main]]
url = "/ru"
name = "Главная"
weight = 200

[[languages.ru.menu.main]]
url = "/ru/about"
name = "Обо мне"
weight = 190

[[languages.ru.menu.main]]
url = "/ru/contact"
name = "Связаяться со мной"
weight = 180

[params]
  cover = "upload/img/standart/backdrop.jpeg"
  
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "CodeEsthete"
  githubName = "CodeEsthete"

  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

